---
roles:
  - src: git@github.com:emmanuelcodes2020/ansible-role-java.git
    name: ansible-role-java
    scm: git
    version: main

  - src: git@github.com:emmanuelcodes2020/ansible-role-sonarqube.git
    name: ansible-role-sonarqube
    scm: git
    version: main